### ISSUE TITLE
Mark beta branch packages as "pre-release"

### ISSUE THREAD

**Issue by welles** [BUTR/Bannerlord.ReferenceAssemblies#5]
Hi there, I've been using the reference assemblies for a while now with great success. Thanks for all your hard work!

I was wondering if you could tag the NuGet packages built against the beta branch of the game as "pre-released" to avoid confusion on which is the latest "stable" version.

Currently you have to check the development blog of the game to check which version is the stable and which is the beta and then reference them directly.

Cheers

**Comment by Aragas** [comment]
This is a great question!

Our non-ideal solution to the 'latest Stable/Beta' problem is to have a [workflow](https://github.com/BUTR/.github/blob/master/.github/workflows/sync.yml) that monitors the latest version available on Steam. If the public version branch does not correspond to our Stable version, then there is a new game release.
We then update in each github project `SYNCED_GAME_STABLE_VERSION`/`SYNCED_GAME_BETA_VERSION` secrets that are used in the workflows for getting the current versions for Stable/Beta from the NuGet packages.

Your suggestion does sound interesting. By taking the latest release/pre-prelease in our mods we can ensure we target the latest Stable/Beta versions in the simpler workflows scenarios.
We have the necessary info about a version being the current Beta when building the package, so this is possible.

There is still the issue of the behavior change. Moving the beta packages to the pre-release channel will break the existing workflows, because they assume the Beta packages are in the release channel.
The only solution I see currently is to duplicate the packages with a different Id.   
`Bannerlord.ReferenceAssemblies.Core.EarlyAccess2` or something. Still not the ideal solution to the problem.

**Comment by Aragas** [comment]
Closing since there was no feedback, assuming the current behavior is acceptable

**Comment by welles** [comment]
Hi there!
It is true, for a long time the current behaviour has been working fine. Recently though I have been playing around with GitHub's dependabot in a testing repository and found a way to make it update stable and beta versions of a referenced Nuget package separately in two branches.
You can check it out here: https://github.com/welles/dependabot_test
I used the package Serilog as a stand-in for what would be the ReferenceAssemblies.
So I wanted to ask you if we could revisit this idea to make beta releases marked a prerelease in Nuget, because this would be a perfect way to update the game version in non-BUTR mods. 
It is true that this change would break existing workflows, but I would also caution against using a new package source for the new system, and instead "bite into the sour apple" - as we would say in Germany :-) - and let workflows break where they must, rather than introduce confusion by having two similarly named package groups. 
I honestly believe this change would be worth the effort now and pay off over the next years.

**Comment by Aragas** [comment]
This concept will work even when the game will release. So we could just keep updating the non-prerelease NuGet packages when they'll stop making betas.
I do believe that the `EarlyAccess` postfix packages don't need such a continuous version delivery, so it still might be a good idea to create `Bannerlord.ReferenceAssemblies.*.Main` packages instead, not sure about the `Main` postfix.
By using those packages we guarantee that the non-pre-release versions will always represent the current stable/release versions and pre-releases will represent beta/nightly(?) builds

**Comment by welles** [comment]
Sounds good! Maybe if it is possible you could use no postfix at all? Just `Bannerlord.ReferenceAssemblies`, `Bannerlord.ReferenceAssemblies.Core` and so on. That would also show that it's the 'main' package.

**Comment by Aragas** [comment]
I agree, but it can bite us later if we'll decide to do some filtration, the postfix is a good way to differentiate EA and the long-term packages

**Comment by welles** [comment]
That's true. How about `Public`, like they use in the Steam depots?

**Comment by Aragas** [comment]
Sounds better than `Main`, we explain it that it mirrors Steam's public/beta system

**Comment by Aragas** [comment]
I guess we can close this now, the release now lost it's *.EarlyAccess suffix, so pre-release is not needed

**Comment by Aragas** [comment]
They reintroduced betas. Well, time to do betas as pre-release!

**Comment by Aragas** [comment]
Done
